[package]
name = "com-api-macros"
version = "0.1.0"
edition = "2024"
publish = ["common"]
license = "Apache-2.0"

[lib]
proc-macro = true

[features]
iceoryx = ["iceoryx2"]

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
iceoryx2 = { git = "https://github.com/eclipse-iceoryx/iceoryx2.git", rev = "d3d1c9a727d3dc405733081923be5dba8213d6d8" , optional = true}
