[package]
name = "com-api-examples"
version = "0.1.0"
edition = "2024"
publish = ["common"]
license = "Apache-2.0"

[features]
mock = ["com-api/mock", "com-api-gen/mock"]
lola = ["com-api/lola", "com-api-gen/lola"]

[dependencies]
com-api = { workspace = true }
com-api-gen = { workspace = true, optional = true }
tokio = { version = "~1.43", features = ["rt-multi-thread", "macros", "test-util"] }

[[example]]
name = "basic-consumer-producer"
path = "basic-consumer-producer.rs"

[[test]]
name = "basic-consumer-producer-test"
path = "basic-consumer-producer.rs"
